name: Deploy to AWS Lambda by open id connect

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      -name: Configure AWS Credentials
       run: |
         export AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}
         export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
         export AWS_DEFAULT_REGION=ap-northeast-1

         echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
         echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
         echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

         curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      - name: Setup Go
        uses: actions/setup-go@v2
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get Dependencies
        run: go get -v
      
      - name: Build
        run: go build -v main.go
      
      - name: Zip
        run: zip function.zip main
      
      - name: Deploy AWS Lambda
        uses: appleboy/lambda-action@master
        run: pip3 install awscli
        run: aws lambda update-function-code --function-name golang-api --zip-file fileb://function.zip --publish
