name: Deploy to Amazon Lambda

on:
  workflow_dispatch:

jobs:
  build:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      
    - name: Checkout
      uses: action/checkout@v2
      
    - name: Get Dependencies
      run: go get -v
      
    - name: Build
      run: go build -v main.go
      
    - name: Zip
      run: zip function.zip main
      
    - name: Deploy AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: golang-api
        zip_file: function.zip
